# Copyright 2014-2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Gather lxc container host facts
  hosts: "{{ lxc_host_group | default('lxc_hosts')}}"
  gather_facts: "{{ gather_facts | default(True) }}"

- name: Install additional packages
  hosts: designate_all
  user: root
  tasks:
    - name: Install packages
      apt: 
        name: "{{ item }}"
        state: installed
      with_items:
        - "git"
        - "bind9utils"

- name: Install Designate Server
  hosts: designate_all
  user: root
  pre_tasks:
    - include: /opt/rpc-openstack/openstack-ansible/playbooks/common-tasks/os-lxc-container-setup.yml
    - include: /opt/rpc-openstack/openstack-ansible/playbooks/common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ designate_rabbitmq_userid }}"
        password: "{{ designate_rabbitmq_password }}"
        vhost: "{{ designate_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ designate_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['designate_all'][0]
        - groups[designate_rabbitmq_host_group] | length > 0
    - include: /opt/rpc-openstack/openstack-ansible/playbooks/common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ designate_galera_user }}"
        password: "{{ designate_galera_password }}"
        login_host: "{{ designate_galera_address }}"
        db_name: "{{ designate_galera_database_name }}"
      when: inventory_hostname == groups['designate_all'][0]
  roles:
    - { role: "os_designate", tags: [ "os-designate" ] }
    - { role: "openstack_openrc", tags: [ "openrc" ] }
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: designate_log_rotate
      rsyslog_client_log_dir: "/var/log/designate"
      rsyslog_client_config_name: "99-designate-rsyslog-client.conf"
      tags:
        - rsyslog
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
  tags:
    - "designate"
     
